### ISSUE TITLE
[Enhancement] Add commas as a thousands separator for mettle

### ISSUE THREAD

**Issue by rexatlanti** [xivapi/XIV-Character-Cards#10]
Title. It gets a bit hard to read and should be easy to format from the raw lodestone input.

**Comment by ArcaneDisgea** [comment]
I'll think on this, currently Mettle is pending removal because after players reach rank 25 lodestone stops displaying it so I am debating whether it is even worth keeping on the cards as it *appears* to be a glorified experience system that can be used as currency and since we don't track elemental exp on the cards either....

Another alternative would be hiding mettle post rank 25 but then we lose some consistency.

**Comment by ArcaneDisgea** [comment]
Yeah, it's unfortunate. Someone brought this up in xivapi this morning and I asked what it showed on lodestone for a rank 25 and apparently lodestone just clears it out.

![image](https://user-images.githubusercontent.com/39720490/120022704-c8e1de00-bfba-11eb-8e5c-572d1c8f68b1.png)

**Comment by ArcaneDisgea** [comment]
Closed by #8 with the removal of mettle from the card.
