### ISSUE TITLE
Level numbers appear on the wrong jobs

### ISSUE THREAD

**Issue by SocMinarch** [xivapi/XIV-Character-Cards#33]
Given the following Lodestone character levels:
![image](https://user-images.githubusercontent.com/6444703/194747025-ca987cab-1ce2-403e-b651-e275dc4d0bf7.png)

These are incorrectly rendered like so:
![image](https://user-images.githubusercontent.com/6444703/194747091-e647342e-f74d-4871-a534-7539b7d98805.png)

The numbers appear to be correct, but they appear on the wrong classes/jobs.

This is when using the public API.

**Comment by SocMinarch** [comment]
Doesn't happen when I run my own instance using the `master` branch

**Comment by ArcaneDisgea** [comment]
Hello, thanks for the report. 

The current version hosted on Heroku is run by another xivapi contributor and has not updated to match what is on the master branch. Due to recent changes with Heroku I believe the intention is for the hosted version to be shut down. 

We highly recommend hosting it yourself or using it as a library if applicable at this time.

I am exploring hosting alternatives to keep *something* up for people to play with but I don't want to set any expectations. The recommended usage will be to host it yourself or use it as a library. If I find a solution I will update the `readme` and this issue.

**Comment by SocMinarch** [comment]
If it helps, I'm currently running the API on a `t3a.nano` instance on AWS Elastic Beanstalk. The only code change required was adding `"engines": { "node" : "v16.17.1" }` to `package.json`.

Running it on the cheaper `t4g.nano` instances was problematic since the dependencies don't have binaries available for ARM64.

**Comment by ArcaneDisgea** [comment]
@SocMinarch 1.5.0 should resolve your arm issues hopefully. Node-Canvas added support for it in a later version than we had been using. Just figured I'd mention since trying to dev this on my mac made that more of a priority to look at.

**Comment by SocMinarch** [comment]
@ArcaneDisgea Thanks for that, I'm working on getting the ELB app defined in Terraform and then I should be able to get a public instance running pretty quickly
